# Generated by Django 4.2.3 on 2023-07-06 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Criacao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('raca', models.CharField(max_length=100, verbose_name='Raça')),
                ('data_entrada', models.DateField(verbose_name='Data de Entrada')),
            ],
        ),
        migrations.CreateModel(
            name='Coleta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateField(verbose_name='Data')),
                ('quantidade', models.IntegerField(verbose_name='Quantidade')),
                ('criacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producao.criacao', verbose_name='Criação')),
            ],
        ),
    ]
